-- Tabela de logs de métricas do sistema do Raspberry Pi
-- Execute no painel do banco de dados (SQL Editor)

create table if not exists public.pi_system_logs (
    id            bigint generated by default as identity primary key,
    site_id       text        not null,
    versao        text        null,
    temp_c        numeric(5,1) null,   -- temperatura da CPU em °C
    ram_pct       numeric(5,1) null,   -- uso de RAM em %
    disk_pct      numeric(5,1) null,   -- uso de disco em %
    cpu_load      numeric(6,2) null,   -- load average 1 min
    wifi_speed_mbps numeric(8,2) null, -- velocidade de download em Mbps
    wifi_ssid     text        null,    -- rede Wi-Fi conectada
    uptime_seconds bigint     null,    -- segundos desde o boot
    logged_at     timestamptz not null default timezone('utc', now())
);

create index if not exists idx_pi_system_logs_site_logged
    on public.pi_system_logs (site_id, logged_at desc);

comment on table public.pi_system_logs is
'Logs periódicos de métricas do sistema (temperatura, RAM, disco, CPU, Wi-Fi) coletados a cada 15 min pelo servidor local.';
