-- Estado atual de métricas do sistema por unidade (uma linha por site_id)
-- Execute no painel do banco de dados (SQL Editor)

create table if not exists public.pi_system_logs (
    id              bigint generated by default as identity primary key,
    site_id         text         not null unique,   -- uma linha por unidade
    versao          text         null,
    temp_c          numeric(5,1) null,              -- temperatura da CPU em °C
    ram_pct         numeric(5,1) null,              -- uso de RAM em %
    disk_pct        numeric(5,1) null,              -- uso de disco em %
    cpu_load        numeric(6,2) null,              -- load average 1 min
    wifi_speed_mbps numeric(8,2) null,              -- velocidade de download em Mbps
    wifi_ssid       text         null,              -- rede Wi-Fi conectada
    uptime_seconds  bigint       null,              -- segundos desde o boot
    logged_at       timestamptz  not null default timezone('utc', now())
);

comment on table public.pi_system_logs is
'Estado atual de métricas do sistema por unidade. Atualizado a cada 15 min pelo servidor local.';

-- Se a tabela já existia sem o unique, rode só este comando:
-- alter table public.pi_system_logs add constraint pi_system_logs_site_id_key unique (site_id);
