-- Historico de eventos das unidades Raspberry
-- Execute no SQL Editor do banco de dados

create table if not exists public.pi_system_events (
    id          bigint generated by default as identity primary key,
    site_id     text        not null,
    event_type  text        not null,
    message     text        null,
    data        jsonb       not null default '{}'::jsonb,
    versao      text        null,
    created_at  timestamptz not null default timezone('utc', now())
);

create index if not exists pi_system_events_site_created_idx
    on public.pi_system_events (site_id, created_at desc);

create index if not exists pi_system_events_type_created_idx
    on public.pi_system_events (event_type, created_at desc);

comment on table public.pi_system_events is
'Historico de eventos emitidos pelos Raspberry, como boot, restart, reboot e atualizacao.';
