-- Rastreabilidade de versao e eventos do agente Raspberry
-- Execute no SQL Editor do Supabase antes de atualizar os Raspberry.

alter table public.tuya_devices
  add column if not exists app_commit text null,
  add column if not exists app_commit_short text null,
  add column if not exists app_branch text null,
  add column if not exists service_started_at timestamptz null,
  add column if not exists last_heartbeat_at timestamptz null;

create table if not exists public.tuya_server_events (
    id          bigint generated by default as identity primary key,
    site_id     text        not null,
    event_type  text        not null,
    app_version text        null,
    commit_sha  text        null,
    message     text        null,
    data        jsonb       not null default '{}'::jsonb,
    created_at  timestamptz not null default timezone('utc', now())
);

create index if not exists tuya_server_events_site_created_idx
    on public.tuya_server_events (site_id, created_at desc);

create index if not exists tuya_server_events_type_created_idx
    on public.tuya_server_events (event_type, created_at desc);
